### ISSUE TITLE
Jeeves fails when configuration contains a job that was trigger by multijob

### ISSUE THREAD

**Issue by itzikb** [nathan-weinberg/jeeves#138]
When running jeeves with a config that has a job triggered by multijob I get the following error:

``` Traceback (most recent call last):
  File "jeeves.py", line 65, in <module>
    run_report(config, blockers, server, header, test_email, no_email)
  File "/home/itbrown/git/jeeves/report.py", line 135, in run_report
    summary['total_success'] = "Total SUCCESS:  {}/{} = {}%".format(num_success, num_jobs, percent(num_success, num_jobs))
  File "/home/itbrown/git/jeeves/functions.py", line 314, in percent
    return round(100 * float(part) / float(whole), 1)
ZeroDivisionError: float division by zero```

**Comment by nathan-weinberg** [comment]
This is a duplicate of #117
